### ISSUE TITLE
Add all remaining validations to create wizard form

### ISSUE THREAD

**Issue by jak-atx** [jooskim/vic#23]
**Details:**
Add any/all remaining form validations and display errors to the vch create wizard

**Acceptance Criteria:**
Verify (check with ux) that all remaining validations are on the form inputs and are outputting the correct errors with correct ux (placement etc)

**Comment by cristianfalcone** [comment]
List of implemented validations can be found here:
https://confluence.eng.vmware.com/display/~cfalcone/Create+VCH+Wizard

**Comment by cristianfalcone** [comment]
@ali5ter @lweitzman @jak-atx @jooskim Please be free to add any missing validation or message updates, I'll add them as soon as I receive updates from the Confluence page [here](https://confluence.eng.vmware.com/display/~cfalcone/Create+VCH+Wizard).

**Comment by ali5ter** [comment]
@cristianfalcone I updated the doc and tried to add regex's
