### ISSUE TITLE
wizard scrollbars on both axis displayed

### ISSUE THREAD

**Issue by ali5ter** [jooskim/vic#28]
The VCH creation wizard displays both horizontal and vertical scrollbars.
![screen shot 2017-08-09 at 2 54 47 pm](https://user-images.githubusercontent.com/265869/29138882-fe84964a-7d12-11e7-9c4d-2c8db7442779.png)

### Steps to reproduce
1. Navigate to VIC plugin view
2. Open VCH tab view
3. Add a new VCH to open creation wizard
4. Resulting wizard displays both scrollbars (see image)

### Expected behavior
Only vertical scrollbar for the content div of the step form should appear when there's overflowing content.

**Comment by jooskim** [comment]
PR #29 does not address the issue for IE11. Will soon make another PR for that.

**Comment by jooskim** [comment]
@ali5ter @lweitzman this branch's build was deployed to the 10.192.93.240 box. Can you try opening it and confirm you are not seeing the scrollbars?

**Comment by ali5ter** [comment]
@jooskim confirm that this issue is fixed (see video on #vic-ux).
Is there any way to reduce load time (see video).

**Comment by jooskim** [comment]
@ali5ter The current way the wizard opens up is that the H5 Client loads the Angular app in a separate iframe tag, meaning it goes fetch resource files again. As such, there really isn't much we could do directly to improve the loading time at this point.
