### ISSUE TITLE
VCH wizard: Storage Capacity: File folder field placeholder truncated

### ISSUE THREAD

**Issue by ali5ter** [jooskim/vic#31]
The input field for the storage capacity file folder field truncates the placeholder text (see image) 
![screen shot 2017-08-09 at 3 20 25 pm](https://user-images.githubusercontent.com/265869/29139899-8b7fc850-7d16-11e7-8402-8b624bfd1755.png)

### Steps to reproduce
1. Navigate to VIC plugin view
2. Open VCH tab view
3. Add a new VCH to open creation wizard
4. Proceed to step 3, Storage Capacity
5. The File folder input field truncates the placeholder text

### Expected behavior
The file folder field should be longer so that the placeholder text is seen

**Comment by cristianfalcone** [comment]
This is resolved in #22. Will close this issue once that PR is merged.
