### ISSUE TITLE
add and delete icons positioning incorrect

### ISSUE THREAD

**Issue by ali5ter** [jooskim/vic#32]
The pattern to add or remove form-blocks or form fields in the creation wizard uses an add and delete icon.

The alignment and separation of these icons is incorrect in most places. An example is the addition or deletion of Container Networks in the Networks step of the wizard (see images)
![screen shot 2017-08-09 at 3 25 47 pm](https://user-images.githubusercontent.com/265869/29140277-f5879c5e-7d17-11e7-99fa-6ee28c77278a.png)
![screen shot 2017-08-09 at 3 26 14 pm](https://user-images.githubusercontent.com/265869/29140280-f7c12c2e-7d17-11e7-9f7c-2ee01c0ae458.png)

### Expected positioning
The Add Icon should vertically align with the label of the form field and should have a 12px separation with the right side of the form field. Where the delete and add icon are shown, both should vertically align and have 12px separation.

Refer to the InVision mocks (see image)...
![screen shot 2017-08-09 at 3 33 32 pm](https://user-images.githubusercontent.com/265869/29140355-34fa5c32-7d18-11e7-83b4-aeda2e8f9de6.png)

**Comment by cristianfalcone** [comment]
This is resolved in #22. Will close this issue once that PR is merged.
