### ISSUE TITLE
Port field too long

### ISSUE THREAD

**Issue by ali5ter** [jooskim/vic#33]
Port field should be wide enough to accept up to 5 numeric chars and subsequently be shorter than the related IP/FQDN input field. An example can be seen at the bottom of the advanced section of the Networks step of the VCH creation wizard (see image).

![screen shot 2017-08-09 at 3 35 40 pm](https://user-images.githubusercontent.com/265869/29140590-fc497fb6-7d18-11e7-8ab4-36d50ea5d773.png)

### Expected behavior
The port field should be shorter (displaying up to 5 numeric characters) and validated as a numeric only field.

**Comment by cristianfalcone** [comment]
Adding this to fields validations issues: #23. Will close it when port field validation is merged.
