### ISSUE TITLE
VCH Wizard: VCH name field placeholder should be default value

### ISSUE THREAD

**Issue by ali5ter** [jooskim/vic#49]
I notice that the placeholder for the name field in the VCH Wizard is 'virtual-container-host'. This was meant as a default VCH name value - A pattern typical to vSphere creation wizards.

Do we have a good way of determining a unique default name?

**Comment by cristianfalcone** [comment]
@ali5ter After discussing with @jak-atx and @jooskim about this, we have concluded that we don't have a good way of determining a unique default name. I can add 'virtual-container-host' as the default value, and if it is already define, then an error message will be shown after clicking 'Next' button. Tell me if you are OK with this and if we should display a different placeholder when there is no value in the field.

**Comment by ali5ter** [comment]
Thanks. Sounds good. This at least aligns with the CLI

**Comment by jak-atx** [comment]
This issue was moved to vmware/vic#6362
