### ISSUE TITLE
Horizontal scrollbar on Getting Started page

### ISSUE THREAD

**Issue by ali5ter** [jooskim/vic#55]
There is always a horizontal scrollbar that appears at the bottom of the Getting Started page in macOS Chrome (see image).

![screen shot 2017-08-23 at 3 26 04 pm](https://user-images.githubusercontent.com/265869/29634369-a90920ea-8817-11e7-9ac2-5d0048dad3a4.png)

I'm using vic-44836534-dev.ova

**Comment by cristianfalcone** [comment]
Fixed in [vic-product PR802](https://github.com/vmware/vic-product/pull/802)

**Comment by jak-atx** [comment]
This issue was moved to vmware/vic#6363
