### ISSUE TITLE
Getting Started: VC credential dialog: Remove close icon

### ISSUE THREAD

**Issue by ali5ter** [jooskim/vic#58]
In the OVA Appliance initialization workflow, a modal dialog is used to gather VC credentials.

This modal contains a close icon in the top right. This is the general pattern but, in this situation, we want to prevent the user from closing the dialog. In fact, it was reported that this close icon did nothing when clicked. Therefore it serves no purpose and should be hidden/removed.

**Comment by cristianfalcone** [comment]
Fixed in [vic-product PR802](https://github.com/vmware/vic-product/pull/802)

**Comment by jak-atx** [comment]
This issue was moved to vmware/vic#6365
