### ISSUE TITLE
Parse and display certificates information in VCH create wizard

### ISSUE THREAD

**Issue by jooskim** [jooskim/vic#69]
**User Statement:**
As a user I would like to see details (e.g. expiry date) of the certificates I am about to upload for use with a new VCH.

**Details:**
After talking with Zach, he suggested that PKI.js is now supported on most major browsers (ref: http://caniuse.com/#feat=cryptography)

**Acceptance Criteria:**
Security section should look like this mockup (https://vmware.invisionapp.com/share/6DDE3344N#/239666171_Create_VCH_Wizard_-_4_Security_-_Advanced_3_-_ALT)

- [x] Investigate what portions of PKI.js should be used
- [ ] Turn the server certificate `type=text` input controls into `type=file`s
- [ ] Implement the functionality according to the UX specs (should handle invalid states)
- [ ] Write unit test cases (should handle invalid states)

**Comment by jak-atx** [comment]
This issue was moved to vmware/vic#6356
