### ISSUE TITLE
Move UI code into new repository

### ISSUE THREAD

**Issue by jooskim** [jooskim/vic#77]
Details:
Pending our repo creation we need to move all of our code over from jooskim/vic/new-master branch into vmware/vic-ui

Acceptance Criteria:
Verify the complete UI application has been migrated to vmware/vic-ui repo

**Comment by jooskim** [comment]
WIP is available at https://github.com/jooskim/vic/tree/new-master

**Comment by jak-atx** [comment]
This issue was moved to vmware/vic#6454
