### ISSUE TITLE
Set up CI/CD pipeline

### ISSUE THREAD

**Issue by jooskim** [jooskim/vic#79]
**User Statement**
As a developer I would want a working CI/CD pipeline set up for VIC Engine UI code so that once a commit/PR to the master branch is merged it should kick off a build and unit tests. Integration tests are run nightly.

**Acceptance Criteria**
- [ ] Set up secrets
- [ ] Set up a task to build Angular
- [ ] Set up a task to Java service
- [ ] Set up a task to package Angular & Java service artifacts
- [ ] Set up a task to publish the packages to GCP
- [ ] Set up a task to notify Slack channel

**Comment by jooskim** [comment]
WIP is available at https://github.com/jooskim/vic/tree/new-master

**Comment by jak-atx** [comment]
This issue was moved to vmware/vic#6455
