### ISSUE TITLE
Investigate Clarity Wizard's navigation and validation process

### ISSUE THREAD

**Issue by jooskim** [jooskim/vic#8]
TBD

Louis' comment:

> wizard navigation
> should the next step in the left nav be active if the current page is filled out?

**Comment by jak-atx** [comment]
I've validated that our wizard is working exactly as per the clarity example wizard https://vmware.github.io/clarity/documentation/wizards If we require this functionality we would need to file an issue with clarity to get it into their queue.

**Comment by jak-atx** [comment]
This issue was moved to vmware/vic#6359
